openapi: 3.0.0
info:
  title: News API
  version: 1.0.0
  description: API for user authentication and managing news articles and preferences.
servers:
  - url: http://localhost/api
paths:
  /user:
    get:
      summary: Get authenticated user details
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                type: object
      tags:
        - User

  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
      tags:
        - Authentication

  /login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Invalid credentials
      tags:
        - Authentication

  /logout:
    post:
      summary: Logout a user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logged out successfully
      tags:
        - Authentication

  /forgot-password:
    post:
      summary: Send password reset link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Password reset link sent
      tags:
        - Authentication

  /reset-password:
    post:
      summary: Reset user password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                token:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
      responses:
        '200':
          description: Password reset successfully
      tags:
        - Authentication

  /articles:
    get:
      summary: Get list of articles
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of articles
      tags:
        - Articles

  /article/{id}:
    get:
      summary: Get details of a specific article
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Article details
        '404':
          description: Article not found
      tags:
        - Articles

  /preferences:
    get:
      summary: Get user preferences
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User preferences
      tags:
        - Preferences

    post:
      summary: Set user preferences
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                preferred_sources:
                  type: array
                  items:
                    type: string
                preferred_categories:
                  type: array
                  items:
                    type: string
                preferred_authors:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Preferences updated
      tags:
        - Preferences

  /news-feed:
    get:
      summary: Fetch news feed based on preferences
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
      responses:
        '200':
          description: News feed
        '404':
          description: Preferences not found
      tags:
        - News Feed

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
